### ISSUE TITLE
Feature: Remove from the bootstrap the online keys

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf#207]
### What is the feature about?

The current bootstrap sends the online keys to API (bootstrap), and the Worker stores it in the[ Key Storage Vault](https://repository-service-tuf.readthedocs.io/en/latest/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-keyvault-backend) (based on the configuration)
This was implemented on the first RSTUF prototype, using the [`LocalKeyStorage`](https://repository-service-tuf.readthedocs.io/en/latest/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-keyvault-backend).

But in a production scenario or even when we have SaaS Key Vaults, the Key Vaults will be read-only. The Workers will only read the keys based on some configuration.
The responsibility/action to add the keys to the Key Vault is for the Key Owners/Administrators, including `LocalKeyStorage`, which is based on filesystem/volume.

The feature is to simplify the bootstrap/ceremony process
- Remove the online Keys from the bootstrap process
- Reduce the number of keys/threshold to 1/1 as the default
- Make the LocalKeyStorage configuration more explicit about the key file name

### Services it relates to

repository-service-for-tuf-cli, repository-service-for-tuf-api, repository-service-for-tuf-worker

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
More elaborated changes to be done:

### Worker

The LocalKeyVault configuration class method needs to be extended with the following parameters:
- Optional `LOCAL_KEYVAULT_SNAPSHOT`: inform the file name, default: `snapshot.key`
- Optional `LOCAL_KEYVAULT_TIMESMAP`: inform the file name, default: `timestamp.key`
- Optional `LOCAL_KEYVAULT_BINS`: inform the file name, default: `bins.key`
- Optional `LOCAL_KEYVAULT_SNAPSHOT_PASSWORD`: inform the password/secret to load the Snapshot key
- Optional `LOCAL_KEYVAULT_TIMESTAMP_PASSWORD`: inform the password/secret to load the Timestamp key
- Optional `LOCAL_KEYVAULT_BINS_PASSWORD`: inform the password/secret to load the BINS key
- Optional `LOCAL_KEYVAULT_SNAPSHOT_TYPE`: cryptography, default: `ed25519`
- Optional `LOCAL_KEYVAULT_TIMESMAP_TYPE`: cryptography, default: `ed25519`
- Optional `LOCAL_KEYVAULT_BINS_TYPE`: cryptography, default: `ed25519`

`services.keyvault.local` can be simplified.
* The method `put` is no longer required
* The method `get` requires some changes:
   - It can use SecuritySystemLib directly to open the file
   - Add parameter `cryptography`. The default is `ed25519` as supported by CLI Ceremony
   - Change parameter `password` as optional. Default is None

`repository.bootstrap` action to store online keys is no longer required.

Documentation needs to be updated showing that the keys need to be added to a Volume accessible by RSTUF Worker.

### API

`bootstrap.RoleSettings.key` is not required anymore in the bootstrap payload.

### CLI

In the `cli.admin.ceremony`
- No longer need to load the online keys
- No need add to the payload the online keys

**Comment by MVrachev** [comment]
What if a user wants to have more than 1 online keys?
What will happen with the variables `LOCAL_KEYVAULT_SNAPSHOT`, `LOCAL_KEYVAULT_TIMESMAP` and `LOCAL_KEYVAULT_BINS`?
Should they be a glob or regex?

If there is more than 1 key what will also happen with the `LOCAL_KEYVAULT_SNAPSHOT_PASSWORD`, `LOCAL_KEYVAULT_TIMESTAMP_PASSWORD` and `LOCAL_KEYVAULT_BINS_PASSWORD` as there most likely will be different passwords for each of the keys.

**Comment by kairoaraujo** [comment]
> What if a user wants to have more than 1 online keys?
> 
> What will happen with the variables `LOCAL_KEYVAULT_SNAPSHOT`, `LOCAL_KEYVAULT_TIMESMAP` and `LOCAL_KEYVAULT_BINS`?
> 
> Should they be a glob or regex?
> 
> 
> 
> If there is more than 1 key what will also happen with the `LOCAL_KEYVAULT_SNAPSHOT_PASSWORD`, `LOCAL_KEYVAULT_TIMESTAMP_PASSWORD` and `LOCAL_KEYVAULT_BINS_PASSWORD` as there most likely will be different passwords for each of the keys.

As the keys are in an online vault, we will support a single key. 
If the vault is compromised, all the keys are comprised. 
More keys would be valid if different cryptography algorithms or different vaults. But I don't think we want to support it at the moment.

**Comment by kairoaraujo** [comment]
Related tasks

- [ ] https://github.com/vmware/repository-service-tuf-worker/issues/170
- [ ] https://github.com/vmware/repository-service-tuf-worker/issues/169
- [ ] https://github.com/vmware/repository-service-tuf-worker/issues/171
- [ ] https://github.com/vmware/repository-service-tuf/issues/213
- [ ] https://github.com/vmware/repository-service-tuf-api/issues/229
- [ ] https://github.com/vmware/repository-service-tuf-api/issues/230
- [ ] https://github.com/vmware/repository-service-tuf-cli/issues/178

**Comment by kairoaraujo** [comment]
After discussing with @lukpueh and @MVrachev, we conclude that the online key keyid/public key is not required.
The online key must be loaded during the signing ceremony to generate the signed Root metadata.
If the key doesn't match the given online key to the RSTUF Worker, it will fail during the bootstrap process.
Two tasks were closed due to it.

**Comment by kairoaraujo** [comment]
I included https://github.com/vmware/repository-service-tuf-cli/issues/219 as we have an open PR in review for it. 🎉

**Comment by kairoaraujo** [comment]
I Included https://github.com/vmware/repository-service-tuf/issues/288 to align the RSTUF containers to the online key.
